services:
  - type: web
    name: ecomops-app-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ecomops-app-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: ecomops-app-redis
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.0
databases:
  - name: ecomops-app-db
    databaseName: ecomops
    user: ecomops_user
    plan: free

services:
  - type: redis
    name: ecomops-app-redis
    ipAllowList: [] # only allow internal connections
    plan: free
